# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |v|
  	v.name="linux_vm2"
  	v.memory = 4096
  end
  config.vm.define :dev do |dev|
    dev.vm.network "private_network", ip: "172.47.7.14"
    #dev.vm.network "public_network"
    #dev.vm.network "forwarded_port", guest: 8761, host: 8761
    dev.vm.provision :shell, path: "bootstrap.sh"
    dev.vm.provision :shell,
      inline: 'PYTHONUNBUFFERED=1 ansible-playbook \
        /vagrant/ansible/dev.yml -c local'
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end